### ISSUE TITLE
Recreate WelcomeMeny

### ISSUE THREAD

**Issue by patrikBLMelander** [stefan-hennings/ATM#5]
String input;
        Välj vad du vill göra:
                "1. Lägg till ny kund
                "2. Anställ någon
                "3. Konto ----> Grenar 1: Öppna nytt  konto, 2: Gör insättning, 3: Gör uttag 
                "4. Lån ----> 1: hantera lån, 2: ansök om nytt lån, 3: gör avbetalning
                "6. Avsluta

**Comment by wakelesstuna** [comment]
Done!
